SHEET_CONFIG = {
    'Apparel': {
        'file': 'Ten_x_You_Product_Database.xlsx',
        'sheet_name': 'Apparel',
        'header_row': 0,
        'key_column': 'Style ID',
        'column_map': {
            'Style ID':                         'style_id',
            'Product Name':                     'product_name',
            'Website Display Name':             'website_name',
            'Product Tagline':                  'tagline',
            'Category':                         'category',
            'Sub-Category':                     'sub_category',
            'Gender':                           'gender',
            'Activity':                         'activity',
            'Best Suited For':                  'best_suited_for',
            'Collection':                       'collection',
            'Available Sizes':                  'available_sizes',
            'Available Colours':                'available_colours',
            'MRP (Rs)':                         'mrp',
            'Selling Price (Rs)':               'selling_price',
            'Fit':                              'fit',
            'Sizing Note':                      'sizing_note',
            'Apparel Type':                     'apparel_type',
            'Fabric/Composition':               'fabric',
            'Fabric/Composition Description':   'fabric_description',
            'Pattern/Texture':                  'pattern_texture',
            'Pattern/Texture Description':      'pattern_texture_description',
            'Stitching Description':            'stitching_description',
            'Breathability':                    'breathability',
            'Stretch':                          'stretch',
            'Fabric Feel':                      'fabric_feel',
            'Reflective Elements':              'reflective_elements',
            'Neck Type':                        'neck_type',
            'Sleeve Type':                      'sleeve_type',
            'Inseam Length':                    'inseam_length',
            'Rise':                             'rise',
            'Pockets':                          'pockets',
            'Drawcords':                        'drawcords',
            'Waistband':                        'waistband',
            'Zip enclosure':                    'zip_enclosure',
            'Detailed Product Description':     'description',
            'Wash Care Instructions':           'wash_care',
            'Expert Review':                    'expert_review',
            'Pair With Options':                'pair_with',
            'Country of Origin':                'country_of_origin',
        }
    },
    'Footwear': {
        'file': 'Ten_x_You_Product_Database.xlsx',
        'sheet_name': 'Footwear',
        'header_row': 0,
        'key_column': 'Style ID',
        'column_map': {
            'Style ID':                     'style_id',
            'Product Name':                 'product_name',
            'Website Display Name':         'website_name',
            'Product Tagline':              'tagline',
            'Category':                     'category',
            'Gender':                       'gender',
            'Activity':                     'activity',
            'Best Suited For':              'best_suited_for',
            'Available Sizes':              'available_sizes',
            'Available Colours':            'available_colours',
            'MRP (Rs)':                     'mrp',
            'Selling Price (Rs)':           'selling_price',
            'Fit':                          'fit',
            'Feet Type Suited':             'feet_type_suited',
            'Lacing/Closure Type':          'lacing_closure',
            'Lace Material':                'lace_material',
            'Upper Material':               'upper_material',
            'Upper Features':               'upper_features',
            'Tongue Material':              'tongue_material',
            'Tongue Features':              'tongue_features',
            'Counter / Heel Material':      'heel_material',
            'Counter / Heel Features':      'heel_features',
            'Midsole Material':             'midsole_material',
            'Midsole Features':             'midsole_features',
            'Insole Type':                  'insole_type',
            'Insole Material':              'insole_material',
            'Insole Features':              'insole_features',
            'Outsole Material':             'outsole_material',
            'Outsole Features':             'outsole_features',
            'Forefoot / Toe':               'forefoot_toe',
            'Spikes':                       'spikes',
            'Waterproof':                   'waterproof',
            'Cushioning':                   'cushioning',
            'Stability':                    'stability',
            'Breathability':                'breathability',
            'Weight':                       'weight',
            'Reflective Details':           'reflective_details',
            'Detailed Product Description': 'description',
            'Care Instructions':            'care_instructions',
            'Expert Review':                'expert_review',
            'Country of Origin':            'country_of_origin',
        }
    },
    'Accessories': {
        'file': 'Ten_x_You_Product_Database.xlsx',
        'sheet_name': 'Accessories',
        'header_row': 0,
        'key_column': 'Style ID',
        'column_map': {
            'Style ID':                     'style_id',
            'Product Name':                 'product_name',
            'Website Display Name':         'website_name',
            'Category':                     'category',
            'Gender':                       'gender',
            'Activity':                     'activity',
            'Best Suited For':              'best_suited_for',
            'Available Sizes':              'available_sizes',
            'Available Colours':            'available_colours',
            'MRP (Rs)':                     'mrp',
            'Selling Price (Rs)':           'selling_price',
            'Material / Composition':       'material',
            'Ventilation':                  'ventilation',
            'Cushioning / Terry':           'cushioning',
            'Functional Features':          'functional_features',
            'Detailed Product Description': 'description',
            'Panels':                       'panels',
            'Structured / Unstructured':    'structure_type',
            'Print / Embroidery':           'print_embroidery',
            'Bill / Visor':                 'bill_visor',
            'Closure Type':                 'closure_type',
            'Inside / Sweatband':           'sweatband',
            'Circumference':                'circumference',
            'Fit':                          'fit',
            'Care Instructions':            'care_instructions',
            'Expert Review':                'expert_review',
            'Country of Origin':            'country_of_origin',
        }
    }
}