SHEET_CONFIG = {
    'Catalog - SKU level - D2C': {
        'file': 'Catalog_Master_-_Ten_x_You.xlsx',
        'read_strategy': 'raw_row_extract',  # use the raw read approach we figured out
        'header_row_index': 2,               # row 3, zero-indexed
        'data_start_index': 3,               # data starts row 4, zero-indexed
        'key_column': 'Item Code',
        'key_type': 'product_id',
        'style_column': 'Style ID',
        'columns_to_keep': [
            'Item Code',
            'Style ID',
            'Product Name',
            'Website Item Name',
            'L1 Category',
            'L2 Category',
            'L3 Category',
            'Gender',
            'Activity',
            'Best for',
            'Collection',
            'Size',
            'Technology',
            'Fit (Apparel)',
            'Colour Key',
            'MRP',
            'Secondary Colour',
            'Fabric',
            'Fabric Breathability',
            'Fabric Texture',
            'Fabric Stretch',
            'Fabric Type',
            'Product Surfacing',
            'Neck Type',
            'Sleeve Type',
            'Pocket Type',
            'Drawcords',
            'Waistband',
            'Features (Apparel)',
            'Country of Origin',
            'Status',
            'Fit (Footwear)',
'Upper Breathability',
'Lacing',
'Shoe Weight',
'Shoe Height',
'Midsole Material',
'Upper Material',
'Insole Type',
'Stability',
'Cushion',
'Features (Footwear)',
        ],
        'column_map': {
            'Item Code':          'product_id',
            'Style ID':           'style_id',
            'Product Name':       'product_name',
            'Website Item Name':  'website_name',
            'L1 Category':        'category_l1',
            'L2 Category':        'category_l2',
            'L3 Category':        'category_l3',
            'Gender':             'gender',
            'Activity':           'activity',
            'Best for':           'best_for',
            'Collection':         'collection',
            'Size':               'size',
            'Technology':         'technology',
            'Fit (Apparel)':      'fit_apparel',
            'Colour Key':         'color_key',
            'MRP':                'mrp',
            'Secondary Colour':   'secondary_color',
            'Fabric':             'fabric',
            'Fabric Breathability': 'breathability',
            'Fabric Texture':     'fabric_texture',
            'Fabric Stretch':     'fabric_stretch',
            'Fabric Type':        'fabric_type',
            'Product Surfacing':  'product_surfacing',
            'Neck Type':          'neck_type',
            'Sleeve Type':        'sleeve_type',
            'Pocket Type':        'pocket_type',
            'Drawcords':          'drawcords',
            'Waistband':          'waistband',
            'Features (Apparel)': 'features',
            'Country of Origin':  'country_of_origin',
            'Status':             'status',
            'Fit (Footwear)':      'fit_footwear',
'Upper Breathability': 'upper_breathability',
'Lacing':              'lacing',
'Shoe Weight':         'shoe_weight',
'Shoe Height':         'shoe_height',
'Midsole Material':    'midsole_material',
'Upper Material':      'upper_material',
'Insole Type':         'insole_type',
'Stability':           'stability',
'Cushion':             'cushion',
'Features (Footwear)': 'features_footwear',
        }
    }
}